name: 'Run UnitTest'
description: 'Run integration tests via Docker'
inputs:
  flatimage:
    description: 'Path to flatimage binary (optional, for integration tests)'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get current user UID and GID
      shell: bash
      id: user_info
      run: |
        echo "uid=$(id -u)" >> $GITHUB_OUTPUT
        echo "gid=$(id -g)" >> $GITHUB_OUTPUT

    - name: Build UnitTest image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.unittest
        push: false
        tags: flatimage-unittest:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        build-args: |
          USER_UID=${{ steps.user_info.outputs.uid }}
          USER_GID=${{ steps.user_info.outputs.gid }}

    - name: Extract distribution name
      shell: bash
      id: dist_name
      run: |
        # Extract the basename without path and extension
        DIST_NAME=$(basename "${{ inputs.flatimage }}" .flatimage)
        echo "dist=$DIST_NAME" >> $GITHUB_OUTPUT

    - name: Run UnitTests
      if: ${{ contains(github.server_url, 'github.com') }}
      shell: bash
      run: |
        echo "Running in GitHub Actions, using direct volume mount"
        # Configure apparmor for ubuntu
        sudo ln -s /usr/bin/sudo /usr/bin/pkexec
        # Run tests directly in the ubuntu runner
        2>&1 ./test/test.py ${{ inputs.flatimage }} \
        | tee test_unittest_${{ steps.dist_name.outputs.dist }}.log
        # Check for errors
        ! grep -E "FAILED.*failures=[0-9]+" test_unittest.log

    - name: Run UnitTests
      if: ${{ !contains(github.server_url, 'github.com') }}
      shell: bash
      run: |
        # Get container ID for volumes-from (for gitea act_runner compatibility)
        CONTAINER_ID=$(hostname)
        echo "Running in containerized environment (act_runner), using --volumes-from"
        # Set permissions to docker regular user
        chown -R ${{ steps.user_info.outputs.uid }}:${{ steps.user_info.outputs.gid }} /workspace/flatimage/flatimage
        # Run docker with current volumes
        2>&1 docker run --privileged \
          --device /dev/fuse \
          --volumes-from "$CONTAINER_ID" \
          -w "$GITHUB_WORKSPACE" \
          --rm flatimage-unittest:latest ${{ inputs.flatimage }} \
        | tee test_unittest_${{ steps.dist_name.outputs.dist }}.log
        # Check for errors
        ! grep -E "FAILED.*failures=[0-9]+" test_unittest.log

    - name: Upload UnitTest logs
      uses: christopherhx/gitea-upload-artifact@v4
      if: always() # Always submit the test file if it exists, even if other steps fail
      with:
        name: logs_unittest_${{ steps.dist_name.outputs.dist }}
        path: test_unittest_${{ steps.dist_name.outputs.dist }}.log
        compression-level: 9
        if-no-files-found: error
        overwrite: false